export declare const blue50: string
export declare const brandBlue1: string
export declare const brandBlue10: string
export declare const brandBlue2: string
export declare const brandBlue3: string
export declare const brandBlue4: string
export declare const brandBlue5: string
export declare const brandBlue6: string
export declare const brandBlue7: string
export declare const brandBlue8: string
export declare const brandBlue9: string
export declare const brandGreen1: string
export declare const brandGreen10: string
export declare const brandGreen2: string
export declare const brandGreen3: string
export declare const brandGreen4: string
export declare const brandGreen5: string
export declare const brandGreen6: string
export declare const brandGreen7: string
export declare const brandGreen8: string
export declare const brandGreen9: string
export declare const brandOrange1: string
export declare const brandOrange10: string
export declare const brandOrange2: string
export declare const brandOrange3: string
export declare const brandOrange4: string
export declare const brandOrange5: string
export declare const brandOrange6: string
export declare const brandOrange7: string
export declare const brandOrange8: string
export declare const brandOrange9: string
export declare const brandPurple1: string
export declare const brandPurple10: string
export declare const brandPurple2: string
export declare const brandPurple3: string
export declare const brandPurple4: string
export declare const brandPurple5: string
export declare const brandPurple6: string
export declare const brandPurple7: string
export declare const brandPurple8: string
export declare const brandPurple9: string
export declare const brandRed1: string
export declare const brandRed10: string
export declare const brandRed2: string
export declare const brandRed3: string
export declare const brandRed4: string
export declare const brandRed5: string
export declare const brandRed6: string
export declare const brandRed7: string
export declare const brandRed8: string
export declare const brandRed9: string
export declare const colorBgBase: string
export declare const colorBrand: string
export declare const colorError: string
export declare const colorInfo: string
export declare const colorSuccess: string
export declare const colorTextBase: string
export declare const colorTextLightSolid: string
export declare const colorWarning: string
export declare const gold1: string
export declare const gold10: string
export declare const gold2: string
export declare const gold3: string
export declare const gold4: string
export declare const gold5: string
export declare const gold6: string
export declare const gold7: string
export declare const gold8: string
export declare const gold9: string
export declare const neutral100: string
export declare const neutral200: string
export declare const neutral400: string
export declare const neutral50: string
export declare const neutral800: string
export declare const neutral900: string
