export declare const bgBrandOrange: string
export declare const bgContainer: string
export declare const bgContainerDisabled: string
export declare const bgElevated: string
export declare const bgLayout: string
export declare const bgTextHover: string
export declare const border: string
export declare const borderSecondary: string
export declare const brandOrange: string
export declare const brandOrangeActive: string
export declare const brandOrangeHover: string
export declare const controlItemBgActive: string
export declare const controlItemBgActiveHover: string
export declare const controlItemBgHover: string
export declare const errorActive: string
export declare const errorBase: string
export declare const errorBg: string
export declare const errorBgHover: string
export declare const errorBorder: string
export declare const errorBorderHover: string
export declare const errorHover: string
export declare const errorText: string
export declare const errorTextActive: string
export declare const errorTextHover: string
export declare const fillAlter: string
export declare const fillSecondary: string
export declare const icon: string
export declare const iconHover: string
export declare const infoActive: string
export declare const infoBase: string
export declare const infoBg: string
export declare const infoBgHover: string
export declare const infoBorder: string
export declare const infoBorderHover: string
export declare const infoHover: string
export declare const infoText: string
export declare const infoTextActive: string
export declare const infoTextHover: string
export declare const itemBgActiveOrange: string
export declare const primaryActive: string
export declare const primaryBase: string
export declare const primaryBg: string
export declare const primaryBgHover: string
export declare const primaryBorder: string
export declare const primaryBorderHover: string
export declare const primaryHover: string
export declare const primaryText: string
export declare const primaryTextActive: string
export declare const primaryTextHover: string
export declare const split: string
export declare const successActive: string
export declare const successBase: string
export declare const successBg: string
export declare const successBgHover: string
export declare const successBorder: string
export declare const successBorderHover: string
export declare const successHover: string
export declare const successText: string
export declare const successTextActive: string
export declare const successTextHover: string
export declare const text: string
export declare const textDescription: string
export declare const textDisabled: string
export declare const textHeading: string
export declare const textPlaceholder: string
export declare const textSecondary: string
export declare const warningActive: string
export declare const warningBase: string
export declare const warningBg: string
export declare const warningBgHover: string
export declare const warningBorder: string
export declare const warningBorderHover: string
export declare const warningHover: string
export declare const warningText: string
export declare const warningTextActive: string
export declare const warningTextHover: string
