import fonts from '@modules/fonts.module.scss'
import {
  lightButtonTheme,
  lightInputTheme,
  lightFormTheme,
  lightBreadcrumbTheme,
  lightPaginationTheme,
  lightUploadTheme,
  lightStepsTheme,
  lightSelectTheme,
  lightRadioTheme,
  lightCheckboxTheme,
  lightSwitchTheme,
  lightDataTableTheme,
  lightTagTheme,
  lightDividerTheme,
  lightProgressTheme,
  lightTabsTheme,
  lightTimePickerTheme,
  lightTooltipTheme,
  lightMenuTheme,
  lightScrollbarTheme,
} from '@/themes/components'
import type { GlobalThemeOverrides } from 'naive-ui'

export const lightGlobalTheme = {
  common: {
    fontFamily: `${fonts.name}, sans-serif`,
    fontFamilyMono: `${fonts.name}, sans-serif`,
    fontWeight: fonts.weightNormal,
    fontWeightStrong: fonts.weightStrong,
  },
  Button: lightButtonTheme,
  Input: lightInputTheme,
  Form: lightFormTheme,
  Breadcrumb: lightBreadcrumbTheme,
  Pagination: lightPaginationTheme,
  Upload: lightUploadTheme,
  Steps: lightStepsTheme,
  Select: lightSelectTheme,
  Radio: lightRadioTheme,
  Checkbox: lightCheckboxTheme,
  Switch: lightSwitchTheme,
  DataTable: lightDataTableTheme,
  Tag: lightTagTheme,
  Divider: lightDividerTheme,
  Tabs: lightTabsTheme,
  TimePicker: lightTimePickerTheme,
  Progress: lightProgressTheme,
  Tooltip: lightTooltipTheme,
  Menu: lightMenuTheme,
  Scrollbar: lightScrollbarTheme,
} satisfies GlobalThemeOverrides
